export const districts = [
    "Srikakulam",
    "Vizianagaram",
    "Visakhapatnam",
    "East Godavari",
    "West Godavari",
    "Krishna",
    "Guntur",
    "Prakasam",
    "Nellore",
    "Kadapa",
    "Anantapur",
    "Chittoor",
    "Kurnool",
]